# Generated by Django 4.1 on 2022-08-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerr',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finalapp.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerr',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finalapp.district'),
            preserve_default=False,
        ),
    ]
