# Generated by Django 4.1 on 2022-08-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_registerr_branch_registerr_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerr',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.branch'),
        ),
        migrations.AlterField(
            model_name='registerr',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.district'),
        ),
    ]
